### ISSUE TITLE
第三章3.4显示有问题

### ISSUE THREAD

**Issue by adamshen** [rocLv/RailsTutorial#1]
这好像是github markdown editor在parse时候的一个bug，不能用粗体标识符来wrapper一个tag，否则就不能正常显示。

```
也就是在我们的页面视图里使用**<title>**标签
```

上面这句话的粗体，在页面上会显示成这样

也就是在我们的页面视图里使用**<title>**标签

**Comment by rocLv** [comment]
因为Markdown本来也允许嵌入HTML标签，这是我写法有问题。
只要转义一下就可以了。
**<title>**

**Comment by adamshen** [comment]
哈哈，原来如此啊。

**Comment by adamshen** [comment]
对了 第三章下面还有没有加转义的HTML标签 

显示然有问题

**Comment by rocLv** [comment]
恩，现在好了。上午急着出去一下。。。
多谢反馈，欢迎传播和贡献
